version: '3'

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.7-alpine
    generator:
        container_name: generator
        build: .
        restart: on-failure
        command: python json_generator.py
        depends_on:
            - rabbitmq
    db:
        container_name: db
        image: postgres:10
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: postgres
    odoo:
        container_name: odoo
        image: odoo
        links:
            - db
        expose:
            - "8069"
        ports:
            - "8069:8069"
    transporter:
        container_name: transporter
        build: .
        restart: on-failure
        command: python data_transporter.py
        depends_on:
            - rabbitmq
            - odoo
